name: Submit Application

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Submit application
        id: submit
        env:
          REPOSITORY_LINK: ${{ github.server_url }}/${{ github.repository }}
          ACTION_RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
        run: python submission.py
